name = "japanese-words-sync"
main = "worker/favorites-worker.js"
compatibility_date = "2026-04-29"
workers_dev = true
preview_urls = false

[vars]
SITE_URL = "https://jiyimianbao.pages.dev"

[triggers]
crons = ["0 16 * * *"]

[[kv_namespaces]]
binding = "FAVORITES"
id = "969904de6cf24fe6982d2b8ee01c9b1a"
