name = "japanese-words-workflow-coordinator"
main = "durable-object/workflow-coordinator.js"
compatibility_date = "2026-04-29"
workers_dev = false
preview_urls = false

[[kv_namespaces]]
binding = "FAVORITES"
id = "969904de6cf24fe6982d2b8ee01c9b1a"

[[durable_objects.bindings]]
name = "WORKFLOW_COORDINATOR"
class_name = "WorkflowCoordinator"

[exports.WorkflowCoordinator]
type = "durable-object"
storage = "sqlite"

[env.preview]
name = "japanese-words-workflow-coordinator-preview"
workers_dev = false
preview_urls = false

[[env.preview.kv_namespaces]]
binding = "FAVORITES"
id = "d4d4852d9be04115830789aaffbf4aca"

[[env.preview.durable_objects.bindings]]
name = "WORKFLOW_COORDINATOR"
class_name = "WorkflowCoordinator"
